[project]
name = "flask-demo"
version = "0.1.0"
description = "Python Demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.3",
    "fastapi[all]>=0.120.4",
    "flask>=3.1.2",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
